image:
  - Visual Studio 2019
  - macOS
  - Ubuntu

skip_branch_with_pr: true
stack: python 3.10

environment:
  GITHUB_TOKEN:
    secure: Ti46nPnZgFh0nRteU6ma0EhJnCTW7PaMn9hnnewZl4gBFPyRQnXNCwGog02+MRLX

install:
  - pip install -r requirements.txt

build_script:
  - flet pack main.py --name unggul_jaya_beton --icon icon.png --product-name unggul_jaya_beton --product-version "1.2.3" --copyright "Copyright (c) 2022 YourCompany Inc."

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
#
for:
  - matrix:
      only:
        - image: Visual Studio 2019

    after_build:
      - 7z a unggul_jaya_beton-windows.zip %CD%\dist\*.exe

    artifacts:
      - path: unggul_jaya_beton-windows.zip

  #
  #   macOS package
  #
  # -
  #   matrix:
  #     only:
  #     - image: macOS

  #   after_build:
  #   - tar -czvf unggul_jaya_beton-macos.tar.gz -C dist unggul_jaya_beton.app

  #   artifacts:
  #   - path: unggul_jaya_beton-macos.tar.gz

  #
  #   Linux package
  #
  - matrix:
      only:
        - image: Ubuntu

    after_build:
      - tar -czvf unggul_jaya_beton-linux.tar.gz -C dist unggul_jaya_beton

    artifacts:
      - path: unggul_jaya_beton-linux.tar.gz
